import { useState } from 'react';
import PageLayout from '../../components/ui/PageLayout';
import { HelpCircle, ChevronDown, ChevronUp, Send, Smartphone, FileQuestion, Mail } from 'lucide-react';
import toast from 'react-hot-toast';

interface FAQItem {
  question: string;
  answer: string;
}

const faqs: FAQItem[] = [
  {
    question: "How does AI Categorization work?",
    answer: "When you enter a transaction title without choosing a category, our engine analyzes the merchant name or keywords (e.g., 'Starbucks', 'Uber') to automatically assign the correct category (e.g., 'Food & Dining', 'Transportation'). It also marks the transaction as 'AI Categorized' with a special status indicator."
  },
  {
    question: "How do I create and manage budgets?",
    answer: "Go to the Budgets page and click 'Create Budget'. You can define a limit for a specific category (e.g. Shopping) or a global budget, set the period (Weekly, Monthly, Yearly), and track your spending against it. The progress bars will change from Green to Yellow and Red as you approach your limit."
  },
  {
    question: "Can I export my transactions data?",
    answer: "Yes, you can export your data in two ways. On the Transactions page, you can export your filtered list as a CSV spreadsheet. On the Reports page, you can request full financial statements as PDFs or CSVs for any date range, directly generated by our backend services."
  },
  {
    question: "What are Recurring Expenses?",
    answer: "Recurring expenses are template schedules for expenses that happen on a regular basis (e.g., Netflix subscription, monthly utilities, rent). You can set their frequency (Daily, Weekly, Monthly, Yearly) and a next due date. A scheduler job runs every day at 1 AM to automatically log these expenses when they become due."
  },
  {
    question: "Is my financial data secure?",
    answer: "Absolutely. All transactions, passwords, and tokens are encrypted and transmitted securely using HTTPS. We use standard JWT (JSON Web Tokens) with a 256-bit security key for sessions, and passwords are encrypted in the database using the salted BCrypt hashing algorithm with a strength of 12."
  }
];

export default function Support() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [message, setMessage] = useState('');
  const [submitting, setSubmitting] = useState(false);

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  const handleContactSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim() || !email.trim() || !message.trim()) {
      toast.error('Please fill in all contact fields');
      return;
    }
    
    setSubmitting(true);
    setTimeout(() => {
      setSubmitting(false);
      setName('');
      setEmail('');
      setMessage('');
      toast.success('Your message has been sent successfully! We will get back to you soon.');
    }, 1200);
  };

  return (
    <PageLayout title="Support & Help">
      <div className="grid-3" style={{ gap: 'var(--space-lg)', alignItems: 'stretch' }}>
        {/* FAQs Accordion */}
        <div className="card" style={{ gridColumn: 'span 2' }}>
          <div className="card-header">
            <h3 className="section-title" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <FileQuestion size={18} className="text-accent" /> Frequently Asked Questions
            </h3>
          </div>
          <div className="card-body" style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {faqs.map((faq, index) => {
              const isOpen = openIndex === index;
              return (
                <div 
                  key={index} 
                  style={{ 
                    border: '1px solid var(--color-border)', 
                    borderRadius: 'var(--radius-md)', 
                    overflow: 'hidden',
                    background: 'rgba(255,255,255,0.02)'
                  }}
                >
                  <button
                    onClick={() => toggleFAQ(index)}
                    style={{
                      width: '100%',
                      padding: '16px',
                      display: 'flex',
                      justifyContent: 'space-between',
                      alignItems: 'center',
                      background: 'none',
                      border: 'none',
                      textAlign: 'left',
                      cursor: 'pointer',
                      color: 'var(--color-text-primary)',
                      fontWeight: 'var(--font-weight-semibold)',
                      fontSize: '14px',
                    }}
                  >
                    <span>{faq.question}</span>
                    {isOpen ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                  </button>
                  {isOpen && (
                    <div 
                      style={{ 
                        padding: '0 16px 16px 16px', 
                        fontSize: '13px', 
                        color: 'var(--color-text-secondary)',
                        lineHeight: '1.6',
                        borderTop: '1px solid rgba(255,255,255,0.05)',
                        paddingTop: '12px'
                      }}
                    >
                      {faq.answer}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>

        {/* Contact Form */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-lg)' }}>
          <div className="card">
            <div className="card-header">
              <h3 className="section-title" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <Mail size={18} className="text-accent" /> Contact Developer
              </h3>
            </div>
            <div className="card-body">
              <form onSubmit={handleContactSubmit}>
                <div className="input-group">
                  <label className="input-label" htmlFor="name">Name</label>
                  <input
                    id="name"
                    className="input"
                    type="text"
                    placeholder="John Doe"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    disabled={submitting}
                  />
                </div>

                <div className="input-group">
                  <label className="input-label" htmlFor="email">Email</label>
                  <input
                    id="email"
                    className="input"
                    type="email"
                    placeholder="john@example.com"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    disabled={submitting}
                  />
                </div>

                <div className="input-group">
                  <label className="input-label" htmlFor="message">Message</label>
                  <textarea
                    id="message"
                    className="textarea"
                    placeholder="How can we help you?"
                    value={message}
                    onChange={(e) => setMessage(e.target.value)}
                    disabled={submitting}
                    rows={4}
                  />
                </div>

                <button 
                  type="submit" 
                  className="btn btn-primary btn-full-width"
                  disabled={submitting}
                  style={{ marginTop: 12 }}
                >
                  <Send size={16} /> {submitting ? 'Sending...' : 'Send Message'}
                </button>
              </form>
            </div>
          </div>

          {/* App Info Card */}
          <div className="card">
            <div className="card-header">
              <h3 className="section-title" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <Smartphone size={18} className="text-accent" /> Application Details
              </h3>
            </div>
            <div className="card-body" style={{ fontSize: '13px', color: 'var(--color-text-secondary)' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
                <span>App Version</span>
                <span style={{ fontWeight: 'bold' }}>v1.0.0</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
                <span>Framework</span>
                <span style={{ fontWeight: 'bold' }}>Spring Boot / React SPA</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
                <span>Database</span>
                <span style={{ fontWeight: 'bold' }}>MySQL 8.0</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span>Deployment</span>
                <span style={{ fontWeight: 'bold' }}>Docker Container</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </PageLayout>
  );
}
